[package]
name = "rln-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
rln = { git = "https://github.com/vacp2p/zerokit", rev = "005393d" }
